import ArticleCard from "@/components/ArticleCard";
import PublicLayout from "@/components/PublicLayout";
import { articles, categories } from "@/data/articles";
import { ArrowDown, ArrowRight, BookOpen, ExternalLink, Feather, Scale, ShieldCheck } from "lucide-react";
import { useEffect } from "react";
import { Link } from "wouter";

export default function Home() {
  useEffect(() => { document.title = "Direito Criminal em perspectiva | Dra. Carla Rodrigues"; }, []);
  return <PublicLayout>
    <section className="relative min-h-[calc(100vh-5rem)] overflow-hidden border-b border-[color:var(--line)]">
      <div className="aurora aurora-one" /><div className="aurora aurora-two" />
      <div className="container relative grid min-h-[calc(100vh-5rem)] items-center gap-12 py-16 lg:grid-cols-[1.08fr_0.92fr] lg:py-20">
        <div className="relative z-10 max-w-3xl"><p className="eyebrow">Conteúdo jurídico criminal · informação com responsabilidade</p><h1 className="mt-7 max-w-4xl font-display text-[clamp(3.7rem,8vw,7.2rem)] font-semibold leading-[0.84] tracking-[-0.045em]">Direito Criminal <em className="font-normal text-[color:var(--amber-dark)]">em perspectiva.</em></h1><p className="mt-8 max-w-2xl text-base leading-8 text-[color:var(--ink-soft)] sm:text-lg">Conteúdo para pessoas que desejam compreender acusações, garantias e procedimentos do processo criminal com clareza, sobriedade e rigor.</p><div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="/artigos" className="button-primary">Explorar artigos <ArrowRight className="size-4" /></Link><a href="https://www.carlaadvocac.click" target="_blank" rel="noreferrer" className="button-secondary">Conheça o site institucional <ExternalLink className="size-4" /></a></div><a href="#artigos-recentes" className="mt-14 inline-flex items-center gap-3 text-xs font-semibold uppercase tracking-[0.2em] text-[color:var(--muted)]"><span className="grid size-9 place-items-center border border-[color:var(--line)]"><ArrowDown className="size-4" /></span> Continuar leitura</a></div>
        <div className="relative mx-auto w-full max-w-[530px] self-end lg:mx-0"><div className="relative ml-auto aspect-[4/5] w-[88%] overflow-hidden border border-white/60 bg-[color:var(--beige)] shadow-[0_30px_80px_rgba(53,34,20,0.16)]"><img src="https://carlaadvocac.click/manus-storage/dra-carla-rodrigues_361a1c91.webp" alt="Retrato profissional da Dra. Carla Rodrigues" className="h-full w-full object-cover object-top" /><div className="absolute inset-x-0 bottom-0 bg-[color:var(--ink)]/88 p-5 text-[color:var(--paper)] backdrop-blur-md"><p className="font-display text-2xl">Dra. Carla Rodrigues</p><p className="mt-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-[color:var(--rose)]">Advogada criminalista · OAB/RS 105.614</p></div></div></div>
      </div>
    </section>
    <section id="artigos-recentes" className="container py-24 sm:py-28"><div className="flex flex-col gap-5 border-b border-[color:var(--line)] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Publicações recentes</p><h2 className="section-title mt-4">Artigos em destaque</h2></div><Link href="/artigos" className="editorial-link inline-flex items-center gap-2 text-sm font-semibold">Ver todos os artigos <ArrowRight className="size-4" /></Link></div><div className="mt-10 grid gap-6 lg:grid-cols-2">{articles.slice(0, 4).map(article => <ArticleCard key={article.id} article={article} />)}</div></section>
    <section className="border-y border-[color:var(--line)] bg-[color:var(--beige)]/65 py-24 sm:py-28"><div className="container grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="eyebrow">Áreas em foco</p><h2 className="section-title mt-4">Temas para compreender o processo penal.</h2><p className="mt-6 max-w-md leading-7 text-[color:var(--ink-soft)]">Navegue por conteúdos introdutórios sobre direitos, garantias e procedimentos.</p></div><div className="grid sm:grid-cols-2">{categories.map((category, index) => <Link href={`/artigos?categoria=${category.slug}`} key={category.slug} className="group border-b border-[color:var(--line)] p-7 transition-colors hover:bg-white/55 sm:nth-[odd]:border-r"><span className="font-display text-sm text-[color:var(--amber-dark)]">0{index + 1}</span><h3 className="mt-3 font-display text-2xl font-semibold">{category.name}</h3><p className="mt-3 text-sm leading-6 text-[color:var(--ink-soft)]">{category.description}</p><ArrowRight className="mt-5 size-4 transition-transform group-hover:translate-x-1" /></Link>)}</div></div></section>
    <section className="container py-24 sm:py-32"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div className="border-t-2 border-[color:var(--amber)] pt-6"><p className="eyebrow">Responsabilidade editorial</p><p className="mt-6 font-display text-3xl leading-snug">“Informação acessível ajuda a compreender direitos e participar do processo de forma mais consciente.”</p></div><div><p className="eyebrow">Sobre a autora</p><h2 className="section-title mt-4">Dra. Carla Rodrigues</h2><p className="mt-7 text-lg leading-8 text-[color:var(--ink-soft)]">Advogada criminalista inscrita na OAB/RS sob o nº 105.614. Este espaço reúne conteúdo informativo para aproximar temas complexos da realidade de quem responde a um processo ou deseja compreender seus direitos.</p><div className="mt-10 grid gap-px bg-[color:var(--line)] sm:grid-cols-3">{[[ShieldCheck,"Conteúdo responsável","Informação geral, sem promessa de resultado."],[BookOpen,"Linguagem acessível","Conceitos apresentados com clareza e contexto."],[Feather,"Postura informativa","Cada caso exige análise individualizada."]].map(([Icon,title,text]) => { const IconComponent = Icon as typeof ShieldCheck; return <div key={String(title)} className="bg-[color:var(--paper)] p-6"><IconComponent className="size-5 text-[color:var(--petrol)]" /><h3 className="mt-5 font-display text-xl font-semibold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[color:var(--muted)]">{String(text)}</p></div>; })}</div><Link href="/sobre" className="button-primary mt-9">Conheça a autora <ArrowRight className="size-4" /></Link></div></div></section>
  </PublicLayout>;
}
